# Generated by Django 4.2.2 on 2023-06-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmt.manager')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmt.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('IP', 'In Progress'), ('F', 'Finalized'), ('C', 'Cancelled')], max_length=2)),
                ('time_spent', models.DurationField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmt.employee')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmt.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('E', 'Employee'), ('C', 'Customer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timer', models.TimeField(auto_now_add=True)),
                ('stop_timer', models.TimeField()),
                ('finished_task', models.BooleanField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmt.employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmt.task')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmt.user'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmt.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmt.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmt.user')),
            ],
        ),
    ]
